# Generated by Django 3.1.5 on 2021-10-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Your Full Name')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Your Email')),
            ],
        ),
    ]
